<a href="https://colab.research.google.com/github/LETICIANAMUTEBI/VU-NAMUTEBI-MBALIISA-LETICIA-Programming-Practice/blob/main/Namutebi_Leticia_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
print('hello,world')

hello,world


In [23]:
print('hello,Leticia')

hello,Leticia


In [24]:
# ============ TOPIC 1A: CONDITIONAL STATEMENTS ============# ---------- Variables ----------
student_name = "Leticia Namutebi"
score = 72

# ---------- if / elif / else ----------
if score >= 80:
    grade = "A"
elif score >= 70:
    grade = "B"
elif score >= 60:
    grade = "C"
else:
    grade = "F"
print(f"{student_name} scored {score} and got grade {grade}")

# ---------- Nested conditions ----------
age = 20
has_id = True
if age >= 18:
    if has_id:
        print("Access granted")
    else:
        print("Please bring your ID")
else:
    print("Too young to enter")

# ---------- Combining conditions (and / or / not) ----------
temperature = 28
is_raining = False
if temperature > 25 and not is_raining:
    print("Good day for a walk")

Leticia Namutebi scored 72 and got grade B
Access granted
Good day for a walk


In [25]:
# ============ TOPIC 1B: LOOPS ============

# ---------- for loop over a list ----------
fruits = ["apple", "mango", "banana"]
for fruit in fruits:
    print(fruit)

# ---------- for loop with range() ----------
for i in range(1, 6):
    print("Square of", i, "is", i ** 2)

# ---------- enumerate(): index + value ----------
for index, fruit in enumerate(fruits, start=1):
    print(index, fruit)

# ---------- while loop ----------
count = 1
while count <= 5:
    print("Count:", count)
    count += 1

# ---------- break and continue ----------
for n in range(1, 11):
    if n == 3:
        continue      # skip 3
    if n == 8:
        break         # stop the loop at 8
    print(n)

# ---------- Nested loop: multiplication table ----------
for i in range(1, 4):
    for j in range(1, 4):
        print(i * j, end="\t")
    print()

# ---------- Data-science style example ----------
salaries = [1200, 1500, 900, 2000]
total = 0
for s in salaries:
    total += s
print("Total:", total, "| Average:", total / len(salaries))

apple
mango
banana
Square of 1 is 1
Square of 2 is 4
Square of 3 is 9
Square of 4 is 16
Square of 5 is 25
1 apple
2 mango
3 banana
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
1
2
4
5
6
7
1	2	3	
2	4	6	
3	6	9	
Total: 5600 | Average: 1400.0


In [26]:
# Even numbers from 1 to 20
for n in range(1, 21):
    if n % 2 == 0:
        print(n, end=" ")
print()

# Keep doubling until above 1000
value = 1
while value <= 1000:
    value *= 2
print("First value above 1000:", value)

2 4 6 8 10 12 14 16 18 20 
First value above 1000: 1024


In [27]:
# ============ TOPIC 2A: FUNCTIONS ============

# ---------- Basic function with a docstring ----------
def greet(name):
    """Return a greeting for the given name."""
    return f"Hello, {name}!"

print(greet("Leticia"))

# ---------- Default arguments ----------
def power(base, exponent=2):
    """Raise base to exponent (default is square)."""
    return base ** exponent

print(power(5))       # 25
print(power(2, 10))   # 1024

# ---------- Returning multiple values ----------
def describe(numbers):
    """Return min, max and mean of a list."""
    return min(numbers), max(numbers), sum(numbers) / len(numbers)

low, high, mean = describe([4, 8, 15, 16, 23, 42])
print("Min:", low, "Max:", high, "Mean:", round(mean, 2))

# ---------- *args and **kwargs ----------
def add_all(*args):
    return sum(args)

def show_info(**kwargs):
    for key, value in kwargs.items():
        print(key, "=", value)

print(add_all(1, 2, 3, 4))
show_info(name="Leticia", course="Python", year=2026)

# ---------- Modular programming: small functions combined ----------
def clean_scores(scores):
    return [s for s in scores if 0 <= s <= 100]

def average(scores):
    return sum(scores) / len(scores)

raw = [45, 88, 105, 67, -3, 92]
print("Average of valid scores:", average(clean_scores(raw)))

Hello, Leticia!
25
1024
Min: 4 Max: 42 Mean: 18.0
10
name = Leticia
course = Python
year = 2026
Average of valid scores: 73.0


In [28]:
# ============ TOPIC 2B: RECURSION ============

def factorial(n):
    """Recursive factorial: n! = n * (n-1)!"""
    if n == 0 or n == 1:       # base case
        return 1
    return n * factorial(n - 1)  # recursive case

print("5! =", factorial(5))    # 120

def fibonacci(n):
    """Return the nth Fibonacci number recursively."""
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

print([fibonacci(i) for i in range(10)])

# ============ TOPIC 2C: LAMBDA FUNCTIONS ============

square = lambda x: x ** 2
print(square(7))

add = lambda a, b: a + b
print(add(3, 4))

numbers = [1, 2, 3, 4, 5, 6]
print(list(map(lambda x: x * 10, numbers)))          # transform
print(list(filter(lambda x: x % 2 == 0, numbers)))   # filter

students = [("Ann", 80), ("Ben", 65), ("Cathy", 92)]
print(sorted(students, key=lambda s: s[1], reverse=True))  # sort by score

5! = 120
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
49
7
[10, 20, 30, 40, 50, 60]
[2, 4, 6]
[('Cathy', 92), ('Ann', 80), ('Ben', 65)]


In [29]:
# ============ TOPIC 3A: LISTS (ordered, changeable) ============
marks = [55, 78, 62, 91]
marks.append(84)            # add to end
marks.insert(1, 70)         # insert at position 1
marks.remove(62)            # remove a value
print(marks)
print("First:", marks[0], "| Last:", marks[-1], "| Slice:", marks[1:3])
marks.sort()
print("Sorted:", marks, "| Length:", len(marks))

# List comprehension
squares = [x ** 2 for x in range(1, 6)]
print(squares)

# ============ TOPIC 3B: TUPLES (ordered, NOT changeable) ============
point = (4, 7)
print(point[0], point[1])
x, y = point                # unpacking
print("x =", x, "y =", y)
# point[0] = 10   # <- would raise TypeError (tuples are immutable)

[55, 70, 78, 91, 84]
First: 55 | Last: 84 | Slice: [70, 78]
Sorted: [55, 70, 78, 84, 91] | Length: 5
[1, 4, 9, 16, 25]
4 7
x = 4 y = 7


In [30]:
# ============ TOPIC 3C: SETS (unique, unordered) ============
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}
print("Union:", a | b)
print("Intersection:", a & b)
print("Difference:", a - b)

# Remove duplicates from a list
emails = ["a@x.com", "b@x.com", "a@x.com"]
print(set(emails))

# ============ TOPIC 3D: DICTIONARIES (key : value) ============
student = {"name": "Leticia", "age": 22, "course": "Data Science"}
student["grade"] = "A"          # add
student["age"] = 23             # update
print(student["name"])
print(student.get("email", "not provided"))   # safe access

for key, value in student.items():
    print(key, "->", value)

# Dictionary comprehension
squares = {n: n ** 2 for n in range(1, 6)}
print(squares)

# Nested structure: list of dictionaries (similar to a table)
records = [
    {"name": "Ann", "score": 80},
    {"name": "Ben", "score": 65},
]
for r in records:
    print(r["name"], r["score"])

Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4}
Difference: {1, 2}
{'b@x.com', 'a@x.com'}
Leticia
not provided
name -> Leticia
age -> 23
course -> Data Science
grade -> A
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
Ann 80
Ben 65


In [31]:
# ============ TOPIC 4A: FILE INPUT / OUTPUT ============

# ---------- Write a text file ----------
with open("notes.txt", "w") as f:
    f.write("Line one\n")
    f.write("Line two\n")

# ---------- Append ----------
with open("notes.txt", "a") as f:
    f.write("Line three\n")

# ---------- Read the whole file ----------
with open("notes.txt", "r") as f:
    content = f.read()
print(content)

# ---------- Read line by line ----------
with open("notes.txt", "r") as f:
    for line in f:
        print(line.strip())

# ---------- CSV file ----------
import csv
rows = [["name", "score"], ["Ann", 80], ["Ben", 65]]
with open("scores.csv", "w", newline="") as f:
    csv.writer(f).writerows(rows)

with open("scores.csv", "r") as f:
    for row in csv.reader(f):
        print(row)

# ---------- JSON file ----------
import json
data = {"name": "Leticia", "courses": ["Python", "Statistics"]}
with open("data.json", "w") as f:
    json.dump(data, f, indent=2)
with open("data.json", "r") as f:
    print(json.load(f))

Line one
Line two
Line three

Line one
Line two
Line three
['name', 'score']
['Ann', '80']
['Ben', '65']
{'name': 'Leticia', 'courses': ['Python', 'Statistics']}


In [32]:
# ============ TOPIC 4B: EXCEPTION HANDLING ============

# ---------- Basic try / except ----------
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Cannot divide by zero")

# ---------- Multiple exceptions + else + finally ----------
def safe_divide(a, b):
    try:
        answer = a / b
    except ZeroDivisionError:
        print("Error: division by zero")
    except TypeError:
        print("Error: both values must be numbers")
    else:
        print("Result:", answer)       # runs only if no error
    finally:
        print("Done.")                 # always runs

safe_divide(10, 2)
safe_divide(10, 0)
safe_divide(10, "a")

# ---------- Handling a missing file ----------
try:
    with open("missing_file.txt") as f:
        print(f.read())
except FileNotFoundError:
    print("File not found, please check the file name")

# ---------- Raising your own exception ----------
def set_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative")
    return age

try:
    set_age(-5)
except ValueError as e:
    print("Caught:", e)

Cannot divide by zero
Result: 5.0
Done.
Error: division by zero
Done.
Error: both values must be numbers
Done.
File not found, please check the file name
Caught: Age cannot be negative


In [34]:
# ============ TOPIC 5A: CLASSES AND OBJECTS ============
class Student:
    school = "Victoria University"       # class attribute

    def __init__(self, name, reg_no):
        self.name = name                  # instance attributes
        self.reg_no = reg_no

    def introduce(self):
        return f"I am {self.name} ({self.reg_no}) at {Student.school}"

s1 = Student("Leticia", "VU001")
s2 = Student("Namutebi", "VU002")
print(s1.introduce())
print(s2.introduce())

# ============ TOPIC 5B: ENCAPSULATION ============
class BankAccount:
    def __init__(self, owner, balance=0):
        self.owner = owner
        self.__balance = balance          # private attribute

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
        else:
            print("Invalid or insufficient funds")

    def get_balance(self):
        return self.__balance

acc = BankAccount("Leticia", 1000)
acc.deposit(500)
acc.withdraw(200)
print("Balance:", acc.get_balance())
# print(acc.__balance)   # <- AttributeError: data is protected

I am Leticia (VU001) at Victoria University
I am Namutebi (VU002) at Victoria University
Balance: 1300


In [35]:
# ============ TOPIC 5C: INHERITANCE ============
class Person:
    def __init__(self, name):
        self.name = name
    def speak(self):
        return f"{self.name} says hello"

class Lecturer(Person):                    # child class
    def __init__(self, name, subject):
        super().__init__(name)             # call parent constructor
        self.subject = subject
    def speak(self):                       # method overriding
        return f"{self.name} teaches {self.subject}"

class Learner(Person):
    def speak(self):
        return f"{self.name} is learning Python"

# ============ TOPIC 5D: POLYMORPHISM ============
people = [Person("Guest"), Lecturer("Dr. Mirembe", "Data Science"), Learner("Leticia")]
for p in people:
    print(p.speak())      # same method name, different behaviour

Guest says hello
Dr. Mirembe teaches Data Science
Leticia is learning Python


In [36]:
# ============ TOPIC 5E: BUILT-IN MODULES ============
import math
import random
from datetime import datetime

print(math.sqrt(144), math.pi)
print(random.randint(1, 10))
print(datetime.now().strftime("%Y-%m-%d"))

# ============ TOPIC 5F: YOUR OWN MODULE ============
with open("mymath.py", "w") as f:
    f.write('''def add(a, b):
    return a + b

def multiply(a, b):
    return a * b
''')

import mymath
print(mymath.add(2, 3), mymath.multiply(4, 5))

# ============ TOPIC 5G: YOUR OWN PACKAGE ============
import os
os.makedirs("mypackage", exist_ok=True)

with open("mypackage/__init__.py", "w") as f:
    f.write("")                             # marks the folder as a package

with open("mypackage/stats_tools.py", "w") as f:
    f.write('''def mean(values):
    return sum(values) / len(values)
''')

from mypackage import stats_tools
print(stats_tools.mean([10, 20, 30]))

# ============ Installing external packages ============
# !pip install faker        # uncomment to install a package from PyPI

12.0 3.141592653589793
8
2026-10-06
5 20
20.0


In [37]:
# ============ TOPIC 6A: NUMPY ============
import numpy as np

# ---------- Arrays ----------
arr = np.array([10, 20, 30, 40, 50])
print(arr, arr.shape, arr.dtype)
print("Mean:", arr.mean(), "| Std:", arr.std(), "| Sum:", arr.sum())
print(arr * 2)                 # vectorised operation, no loop needed
print(arr[arr > 25])           # boolean filtering

# ---------- Useful generators ----------
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.zeros((2, 3)))
print(np.random.randint(1, 100, size=5))

# ---------- Matrices ----------
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A + B:\n", A + B)
print("Element-wise A * B:\n", A * B)
print("Matrix product A @ B:\n", A @ B)
print("Transpose:\n", A.T)
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))

# ---------- Reshape and slicing ----------
m = np.arange(1, 13).reshape(3, 4)
print(m)
print("Row 1:", m[1], "| Column 2:", m[:, 2], "| Sub-matrix:\n", m[0:2, 1:3])

[10 20 30 40 50] (5,) int64
Mean: 30.0 | Std: 14.142135623730951 | Sum: 150
[ 20  40  60  80 100]
[30 40 50]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[75 47 64 48 84]
A + B:
 [[ 6  8]
 [10 12]]
Element-wise A * B:
 [[ 5 12]
 [21 32]]
Matrix product A @ B:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row 1: [5 6 7 8] | Column 2: [ 3  7 11] | Sub-matrix:
 [[2 3]
 [6 7]]
